<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <GenerateDocumentationFile>false</GenerateDocumentationFile>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    </PropertyGroup>
    <ItemGroup>
        <ProjectReference Include="../ImGuiPlayground/ImGuiPlayground.csproj" />
        <Reference Include="Brutal.Glfw"><HintPath>$(_PlaygroundKsaFolder)Brutal.Glfw.dll</HintPath></Reference>
        <Reference Include="Brutal.ImGui"><HintPath>$(_PlaygroundKsaFolder)Brutal.ImGui.dll</HintPath></Reference>
        <Reference Include="Brutal.Core.Common"><HintPath>$(_PlaygroundKsaFolder)Brutal.Core.Common.dll</HintPath></Reference>
        <Reference Include="Brutal.Core.Numerics"><HintPath>$(_PlaygroundKsaFolder)Brutal.Core.Numerics.dll</HintPath></Reference>
    </ItemGroup>
</Project>
